version: '3.9'

services:
  web:
    build: .
    command: gunicorn gie_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ytj5ars5xlyaw9sd6t8uoc-^f5=)6p4!j_j2jnffc08xf@+3zd
      DEBUG: "True"
      EMAIL_HOST_USER: gieintelligence@gmail.com
      EMAIL_HOST_PASSWORD: olxq zeok imef ofve
      DATABASE_URL: postgresql://gie_db_user:gie_db_pass@db:5432/gie_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gie_db
      POSTGRES_USER: gie_db_user
      POSTGRES_PASSWORD: gie_db_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
