# Generated by Django 4.2.21 on 2025-06-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('ventas', '0005_alter_venta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoriaVenta',
        ),
    ]
