# Generated by Django 4.2.21 on 2025-05-31 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaje',
            name='empleado',
        ),
        migrations.AddField(
            model_name='fichaje',
            name='usuario',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
